sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t dokumansky/webrtc-samples -f Dockerfile .
deply:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "webrtc"
  env: "Webrtc-env"
  bucket_name: "elasticbeanstalk-us-west-2-730376649188"
  bucket_path: "webrtc"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
